import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { root, UIBuilder } from "melony";
import { redirect } from "next/navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: UIBuilder;
}>) {
  return root()
    .appName("Melony Docs")
    .child(children)
    .shouldRenderHtml()
    .className(geistSans.className + " " + geistMono.className)
    .navigate(async (path) => {
      "use server";
      redirect(path);
    })
    .build();
}
