"use client";
import { Check, ChevronDown, ChevronUp, Copy } from "lucide-react";
import {
  type ButtonHTMLAttributes,
  forwardRef,
  type HTMLAttributes,
  type ReactNode,
  useCallback,
  useRef,
  useState,
  useEffect,
} from "react";
import { cn } from "@/lib/utils";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import { useCopyButton } from "@/hooks/use-copy-button";
import { Button, buttonVariants } from "@/components/ui/button";
import {
  ScrollAreaViewport,
  type ScrollAreaViewportProps,
} from "@radix-ui/react-scroll-area";
import { codeToHtml } from "shiki";
import { useTheme } from "next-themes";

export type CodeBlockProps = HTMLAttributes<HTMLElement> & {
  /**
   * Icon of code block
   *
   * When passed as a string, it assumes the value is the HTML of icon
   */
  icon?: ReactNode;

  /**
   * Allow to copy code with copy button
   *
   * @defaultValue true
   */
  allowCopy?: boolean;

  /**
   * Keep original background color generated by Shiki or Rehype Code
   *
   * @defaultValue false
   */
  keepBackground?: boolean;

  /**
   * Allow to expand/collapse the code block
   *
   * @defaultValue false
   */
  expandable?: boolean;

  /**
   * Initial expanded state
   *
   * @defaultValue false
   */
  defaultExpanded?: boolean;

  viewportProps?: ScrollAreaViewportProps;
};

export const Pre = forwardRef<HTMLPreElement, HTMLAttributes<HTMLPreElement>>(
  ({ className, ...props }, ref) => {
    return (
      <pre
        ref={ref}
        className={cn("p-4 focus-visible:outline-none", className)}
        {...props}
      >
        {props.children}
      </pre>
    );
  }
);

Pre.displayName = "Pre";

export const CodeBlock = forwardRef<HTMLElement, CodeBlockProps>(
  (
    {
      title,
      allowCopy = true,
      keepBackground = false,
      icon,
      viewportProps,
      expandable = true,
      defaultExpanded = false,
      ...props
    },
    ref
  ) => {
    const areaRef = useRef<HTMLDivElement>(null);
    const [htmlCode, setHtmlCode] = useState<string>("");
    const [isExpanded, setIsExpanded] = useState(defaultExpanded);
    const [needsExpand, setNeedsExpand] = useState(false);
    const { theme } = useTheme();

    useEffect(() => {
      const checkHeight = () => {
        if (areaRef.current) {
          const pre = areaRef.current.getElementsByTagName("pre").item(0);
          if (pre) {
            const needsExpand = pre.scrollHeight > 200;
            setNeedsExpand(needsExpand);
            if (!needsExpand) {
              setIsExpanded(true);
            }
          }
        }
      };

      checkHeight();
      // Add resize observer to check height when content changes
      const resizeObserver = new ResizeObserver(checkHeight);
      if (areaRef.current) {
        resizeObserver.observe(areaRef.current);
      }

      return () => {
        resizeObserver.disconnect();
      };
    }, [htmlCode]);

    useEffect(() => {
      const renderCode = async () => {
        if (typeof props.children === "string") {
          const html = await codeToHtml(props.children, {
            lang: props.lang ?? "javascript",
            themes: {
              dark: "github-dark",
              light: "github-light",
            },
            // defaultColor: false,
          });

          setHtmlCode(html);
        }
      };

      renderCode();
    }, [props.children, props.lang, theme]);

    const onCopy = useCallback(() => {
      const pre = areaRef.current?.getElementsByTagName("pre").item(0);

      if (!pre) return;

      const clone = pre.cloneNode(true) as HTMLElement;
      clone.querySelectorAll(".nd-copy-ignore").forEach((node) => {
        node.remove();
      });

      void navigator.clipboard.writeText(clone.textContent ?? "");
    }, []);

    return (
      <figure
        ref={ref}
        {...props}
        className={cn(
          "not-prose group relative overflow-hidden rounded-lg border text-sm",
          keepBackground ? "bg-muted" : "bg-white dark:bg-zinc-950",
          "transition-colors duration-200",
          props.className
        )}
      >
        {title ? (
          <div className="flex items-center gap-2 border-b bg-muted/50 dark:bg-zinc-900/50 px-4 py-1.5 transition-colors duration-200">
            {icon ? (
              <div
                className="text-muted-foreground [&_svg]:size-3.5"
                dangerouslySetInnerHTML={
                  typeof icon === "string"
                    ? {
                        __html: icon,
                      }
                    : undefined
                }
              >
                {typeof icon !== "string" ? icon : null}
              </div>
            ) : null}
            <figcaption className="flex-1 truncate text-muted-foreground">
              {title}
            </figcaption>
            <div className="flex items-center gap-2">
              {expandable && needsExpand && (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => setIsExpanded(!isExpanded)}
                  aria-label={isExpanded ? "Collapse code" : "Expand code"}
                >
                  {isExpanded ? (
                    <ChevronUp className="size-3.5" />
                  ) : (
                    <ChevronDown className="size-3.5" />
                  )}
                </Button>
              )}
              {allowCopy ? (
                <CopyButton className="-me-2" onCopy={onCopy} />
              ) : null}
            </div>
          </div>
        ) : (
          <div className="absolute right-2 top-2 z-[2] flex items-center gap-2 backdrop-blur-md">
            {expandable && needsExpand && (
              <button
                type="button"
                onClick={() => setIsExpanded(!isExpanded)}
                className={cn(
                  buttonVariants({
                    variant: "ghost",
                  }),
                  "transition-opacity group-hover:opacity-100 [&_svg]:size-3.5",
                  "[@media(hover:hover)]:opacity-0",
                  "dark:hover:bg-zinc-800 hover:bg-zinc-100"
                )}
                aria-label={isExpanded ? "Collapse code" : "Expand code"}
              >
                {isExpanded ? (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="m18 15-6-6-6 6" />
                  </svg>
                ) : (
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="24"
                    height="24"
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                  >
                    <path d="m6 9 6 6 6-6" />
                  </svg>
                )}
              </button>
            )}
            {allowCopy && <CopyButton onCopy={onCopy} />}
          </div>
        )}
        <ScrollArea ref={areaRef} dir="ltr">
          <ScrollAreaViewport
            {...viewportProps}
            className={cn(
              "max-h-[600px] transition-all duration-200 relative",
              !isExpanded && expandable && needsExpand && "max-h-[200px]",
              viewportProps?.className
            )}
          >
            <div
              className="[&_pre]:!p-4"
              dangerouslySetInnerHTML={{
                __html: htmlCode,
              }}
            />
          </ScrollAreaViewport>
          <ScrollBar orientation="horizontal" />

          {!isExpanded && expandable && needsExpand && (
            <div className="absolute inset-x-0 bottom-0 h-8 bg-gradient-to-t from-background to-transparent" />
          )}
        </ScrollArea>
      </figure>
    );
  }
);

CodeBlock.displayName = "CodeBlock";

function CopyButton({
  className,
  onCopy,
  ...props
}: ButtonHTMLAttributes<HTMLButtonElement> & {
  onCopy: () => void;
}) {
  const [checked, onClick] = useCopyButton(onCopy);

  return (
    <button
      type="button"
      className={cn(
        buttonVariants({
          variant: "ghost",
        }),
        "transition-opacity group-hover:opacity-100 [&_svg]:size-3.5",
        !checked && "[@media(hover:hover)]:opacity-0",
        "dark:hover:bg-zinc-800 hover:bg-zinc-100",
        className
      )}
      aria-label={checked ? "Copied Text" : "Copy Text"}
      onClick={onClick}
      {...props}
    >
      <Check className={cn("transition-transform", !checked && "scale-0")} />
      <Copy
        className={cn("absolute transition-transform", checked && "scale-0")}
      />
    </button>
  );
}
